### ISSUE TITLE
Predictive text on training provider drop down

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#152]
Not working?
![Screenshot 2019-09-11 at 13 10 19](https://user-images.githubusercontent.com/38726669/64696145-9d8d2780-d495-11e9-9805-0e2a125bfeb0.png)

**Comment by benilovj** [comment]
@laurahermionetennant92 as far as I can see, this is just returning all results with the letter 'a'? Presumably we would want to sort the responses alphabetically? If I type 'UCL' it does return the correct result. What other changes would we want to make to this functionality?

**Comment by paulrobertlloyd** [comment]
I have updated this so that it only returns results once you have entered 2 characters or more, which makes this feel a little less flakey.
