### ISSUE TITLE
Apply for postgraduate teacher training header link wrong

### ISSUE THREAD

**Issue by gemmasay** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#164]
The top banner link of 'Apply for postgraduate teacher training' links back to the very start page with the sign in link. I think from a user perspective, this should link back to the 'Your application' page.

![Capture](https://user-images.githubusercontent.com/45398915/64945392-540f5480-d868-11e9-82d7-053382ef87b8.PNG)

**Comment by paulrobertlloyd** [comment]
This should be fixed @gemmasay (tweaked this last week). Let me know if this is still not quite right.

**Comment by gemmasay** [comment]
Awesome - I hadn't re-checked it since, thanks!
