### ISSUE TITLE
Sign-in flow currently broken

### ISSUE THREAD

**Issue by benilovj** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#165]
To reproduce:

1. Click the "sign-in" link on the Start page (`If you have teacher training applications in progress, please sign in`)
2. Provide email address
3. Follow the email link
4. Expected: see your application, actual: error message "Cannot convert undefined or null to object"

**Comment by paulrobertlloyd** [comment]
Ah, so this will only work if you have already started an application; we should put in a redirect here in case you haven’t.

**Comment by paulrobertlloyd** [comment]
The redirect was there, but the code wasn’t robust enough. Fixed!
