### ISSUE TITLE
Need an ability to review and edit course location (if applicable)

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#187]
Currently course selection on the main application page doesn’t display course location, or provide a means of changing it:

![Example](https://user-images.githubusercontent.com/813383/65340771-dda38700-dbc6-11e9-9582-62dc1127e406.png)

However, we do show this information on the review application page:

![Example 2](https://user-images.githubusercontent.com/813383/65340869-0d528f00-dbc7-11e9-80b7-f98548ef61c4.png)

/cc @fofr

**Comment by fofr** [comment]
👍 I had a similar design with the old summary box layout. I think this works, but then wondered whether the courses stuff should move off the application pages and onto its own Courses one.

This was my earlier design on this branch: https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/tree/move-courses

![Screen Shot 2019-09-23 at 08 00 26](https://user-images.githubusercontent.com/319055/65406713-4ca3fa00-ddd8-11e9-998b-39040097d5e9.png)
![Screen Shot 2019-09-23 at 08 00 43](https://user-images.githubusercontent.com/319055/65406714-4ca3fa00-ddd8-11e9-98e9-a0e40e9e550e.png)

**Comment by fofr** [comment]
Fixed in #234
