### ISSUE TITLE
Add line of explanation here

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#206]
![Screenshot 2019-09-26 at 16 09 25](https://user-images.githubusercontent.com/38726669/65700762-171d3c00-e078-11e9-8ff1-8c3f6d3bcf04.png)
Soz, can't work out how to do this.
Underneath this, please can we have: 
'If you delete this entry, you'll be able to add another job or otherwise explain the gap in your work history.'

**Comment by laurahermionetennant92** [comment]
So copy reads:
Are you sure you want to delete this gap entry?
If you delete this entry, you'll be able to add another job or otherwise explain the gap in your work history.
Yes I'm sure – delete this gap entry

**Comment by paulrobertlloyd** [comment]
After speaking with @laurahermionetennant92, we’re going to test this before making further changes.
