### ISSUE TITLE
We're sorry box

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#215]
![Screenshot 2019-10-08 at 13 52 25](https://user-images.githubusercontent.com/38726669/66397104-0606f000-e9d3-11e9-947e-af9652d00307.png)
I was trying to do some paragraph breaks in this but couldn't make it work. Needs to be all bold but in separate pars.

**Comment by paulrobertlloyd** [comment]
This has been updated based on our conversation. Have a look and see what you think.
