### ISSUE TITLE
Specific instance of this page possible?

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#216]
I'd like to have this content be: 

You can apply to your chosen teacher training course using UCAS. You’ll need these codes for the Choices section of your UCAS application form:
![Screenshot 2019-10-08 at 13 58 45](https://user-images.githubusercontent.com/38726669/66397483-d3112c00-e9d3-11e9-8a8e-8c7e958e88a8.png)

**Comment by laurahermionetennant92** [comment]
I think I'll need to explain in person

**Comment by paulrobertlloyd** [comment]
Está feito!
