### ISSUE TITLE
links in footer on apply

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#230]
Just realised that this isn't underlined unless you hover, which is why it doesn't look like a link:
![Screenshot 2019-10-16 at 11 03 49](https://user-images.githubusercontent.com/38726669/66909514-cc526c80-f004-11e9-9a47-4228197da50f.png)

**Comment by paulrobertlloyd** [comment]
This follows the GOV.UK design component guidance (which removed underlines for most links in the footer for v3.0.0). We should test this, and update if necessary, feeding any findings back to GDS.
