### ISSUE TITLE
Content for tick box to confirm only one offer accepted

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#278]
![Screenshot 2019-11-05 at 16 35 34](https://user-images.githubusercontent.com/38726669/68226702-672ddd80-ffea-11e9-8c7b-60c33b48d9cb.png)

**Comment by paulrobertlloyd** [comment]
Fixed in `make-decision` branch.
