### ISSUE TITLE
Working days calculator

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#280]
By my reckoning 40 working days takes them to the 6th January?

![Screenshot 2019-11-06 at 10 49 06](https://user-images.githubusercontent.com/38726669/68292144-246c1400-0083-11ea-9833-ce08a481332d.png)

**Comment by paulrobertlloyd** [comment]
Our calculations are pretty dumb: today’s date plus 40. So the end date will always be wrong. Hopefully nobody will notice 😆

**Comment by paulrobertlloyd** [comment]
Perhaps I should make the calculation plus 56 days, which is likely to be closer to the real date.

**Comment by paulrobertlloyd** [comment]
Fixed in `make-decision` branch.
