### ISSUE TITLE
Working days part 2

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#281]
These dates mean we've given them 3 working days (and 5 actual days). Regardless of whether we surface the working days (and I think we should because it's confusing not to) this date should be 13th Nov...
![Screenshot 2019-11-06 at 10 51 53](https://user-images.githubusercontent.com/38726669/68292415-b3792c00-0083-11ea-9c0a-e84d56882b5c.png)

**Comment by paulrobertlloyd** [comment]
Assuming we always test on a weekday, I can change this date to be +7 days.

**Comment by paulrobertlloyd** [comment]
Fixed in `make-decision` branch.
