### ISSUE TITLE
Need help side bar on Accept and Decline pages

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#283]
Can we add to these pages please
![Screenshot 2019-11-06 at 11 37 12](https://user-images.githubusercontent.com/38726669/68295260-e58d8c80-0089-11ea-9f7e-4cc39750c1ed.png)

**Comment by paulrobertlloyd** [comment]
Have added, but may want to review with Juan as there have been some changes w/r/t our support model.
