### ISSUE TITLE
Needs to display 'Withdrawn' after candidate has accepted

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#284]
Strictly speaking, after the candidate has accepted an offer, the second offer on this page should say Withdrawn.

**We also need some different content at the bottom, ie:**

Next steps

We'll send you an email to confirm you've accepted an offer, and we'll also inform your training provider.

Your training provider will then be in touch with you direct to explain what to do next.

For help with an aspect of your application journey, you can also register with Get into Teaching.
![Screenshot 2019-11-06 at 11 40 00](https://user-images.githubusercontent.com/38726669/68295821-2043f480-008b-11ea-85b5-5edc7ad890e7.png)

**Comment by paulrobertlloyd** [comment]
Fixed in `make-decision` branch, but have amended the guidance as this needs to be persistent content, not just guidance that appears after you’ve accepted.
