### ISSUE TITLE
Confirmation: Application submitted email

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#286]
Can you put in placeholder for ((date5workingdaysfromsubmission)) – not sure what it should be 
![Screenshot 2019-11-06 at 13 34 39](https://user-images.githubusercontent.com/38726669/68302791-956af600-009a-11ea-8d83-f5df3c38a99a.png)

**Comment by paulrobertlloyd** [comment]
Done.
