### ISSUE TITLE
'Add course' when amending application

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#287]
Keeping a note of Slack discussion:
It appears on the course choices page, perhaps it should be here too? Note however that in the above state shown, they haven’t started amending their application, so a button wouldn’t appear
![Screenshot 2019-11-06 at 13 35 31](https://user-images.githubusercontent.com/38726669/68317264-bd665380-00b2-11ea-8b31-9bd6dc8c4c0d.png)

Ah I see, I think in an ideal world it should be, and actually, re our previous discussion, this kind of looks like you can edit your application but not your courses. It looks as though we’re displaying them separately as if they’re different from the application, and somehow not available for editing.

**Comment by paulrobertlloyd** [comment]
Fixed in `make-decision` branch. Add button and delete links only show once you have explicitly entered edit mode, though.
