### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/apply-for-postgraduate-teacher-training-prototype#57]
![Screenshot 2019-08-06 at 11 06 15](https://user-images.githubusercontent.com/38726669/62531385-419e0600-b83a-11e9-8bfc-7f78bb9f8e0b.png)
In an earlier version did we have Dashboard small and grey above the heading?

**Comment by paulrobertlloyd** [comment]
We did… can’t remember why I removed it!
